### ISSUE TITLE
How can I query the parameters of the network?

### ISSUE THREAD

**Issue by Merida222** [ltzheng/pddpg-hfo#1]
I want to query the parameters of the network, but the function "query_all_policies" seems not to work, because " ValueError: could not convert string to float:'Parameter'. How can I query the parameters of the network? Or is there another way to make all robots share a critic network？Thank you!

**Comment by ltzheng** [comment]
Sorry for the delay, the code for redis and maddpg is not thoroughly tested and is not recommended to use.
To make all bots share a network, you can modify the layers in the model as python global variables. See [ray/rllib/examples/models/shared_weights_model.py](https://github.com/ray-project/ray/blob/master/rllib/examples/models/shared_weights_model.py).
